# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-03 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_auto_20200802_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
