# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-03 15:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_auto_20200803_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
