# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-03 16:02
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200802_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='content',
        ),
        migrations.AddField(
            model_name='services',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
