# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-03 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20200803_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
